package edu.illinois.awikum.mp7;

import android.support.v4.app.Fragment;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ArrayAdapter;
import android.widget.AutoCompleteTextView;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextView;

import com.android.volley.Request;
import com.android.volley.RequestQueue;
import com.android.volley.Response;
import com.android.volley.VolleyError;
import com.android.volley.toolbox.JsonObjectRequest;
import com.android.volley.toolbox.Volley;

import org.json.JSONException;
import org.json.JSONObject;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

public class stocks extends Fragment{
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View rootView = inflater.inflate(R.layout.stocks, container, false);

        String COUNTRIES[]={"AGILENT TECHNOLOGIES INC (A) ","ALCOA CORP (AA)",
                "ALTABA INC (AABA)",
                "AAC HOLDINGS INC (AAC)",
                "ADVISORSHARES DORSEY WRIGHT (AADR)",
                "AMERICAN AIRLINES GROUP INC (AAL)",
                "ALTISOURCE ASSET MANAGEMENT (AAMC)",
                "ATLANTIC AMERICAN CORP (AAME)",
                "AARON'S INC (AAN)",
                "APPLIED OPTOELECTRONICS INC (AAOI)",
                "AAON INC (AAON)",
                "ADVANCE AUTO PARTS INC (AAP)",
                "APPLE INC (AAPL)",
                "AMERICAN ASSETS TRUST INC (AAT)",
                "ALMADEN MINERALS LTD - B (AAU)",
                "ADVANTAGE OIL & GAS LTD (AAV)",
                "ATLAS AIR WORLDWIDE HOLDINGS (AAWW)",
                "ISHARES MSCI ALL COUNTRY ASI (AAXJ)",
                "AXON ENTERPRISE INC (AAXN)",
                "ALLIANCEBERNSTEIN HOLDING LP (AB)",
                "RENMIN TIANLI GROUP INC (ABAC)",
                "ABAXIS INC (ABAX)",
                "ABB LTD-SPON ADR (ABB)",
                "ABBVIE INC (ABBV)",
                "AMERISOURCEBERGEN CORP (ABC)",
                "AMERIS BANCORP (ABCB)",
                "CAMBIUM LEARNING GROUP INC (ABCD)",
                "ALCENTRA CAPITAL CORP (ABDC)",
                "ABERDEEN EMERGING MARKETS SM (ABE)",
                "ABEONA THERAPEUTICS INC (ABEO)",
                "AMBEV SA-ADR (ABEV)",
                "ASBURY AUTOMOTIVE GROUP (ABG)",
                "ABILITY INC (ABIL)",
                "ARCA BIOPHARMA INC (ABIO)",
                "ABLYNX NV - SPONSORED ADR (ABLX)",
                "ABM INDUSTRIES INC (ABM)",
                "ABIOMED INC (ABMD)",
                "ARBOR REALTY TRUST INC (ABR)",
                "ABBOTT LABORATORIES (ABT)",
                "ALLEGIANCE BANCSHARES INC (ABTX)",
                "ARBUTUS BIOPHARMA CORP (ABUS)",
                "BARRICK GOLD CORP (ABX)",
                "ASSOCIATED CAPITAL GROUP - A (AC)",
                "ACADIA PHARMACEUTICALS INC (ACAD)",
                "ATLANTIC CAPITAL BANCSHARES (ACBI)",
                "AMERICAN CAMPUS COMMUNITIES (ACC)",
                "ACCO BRANDS CORP (ACCO)",
                "ACER THERAPEUTICS INC (ACER)",
                "ACETO CORP (ACET)",
                "ATLANTIC COAST FINANCIAL COR (ACFC)",
                "ARCH CAPITAL GROUP LTD (ACGL)",
                "ALUMINUM CORP OF CHINA-ADR (ACH)",
                "ACADIA HEALTHCARE CO INC (ACHC)",
                "ACHILLION PHARMACEUTICALS (ACHN)",
                "ACHIEVE LIFE SCIENCES INC (ACHV)",
                "ACACIA COMMUNICATIONS INC (ACIA)",
                "SPDR MSCI ACWI IMI ETF (ACIM)",
                "AC IMMUNE SA (ACIU)",
                "ACI WORLDWIDE INC (ACIW)",
                "AXCELIS TECHNOLOGIES INC (ACLS)",
                "AECOM (ACM)",
                "ACM RESEARCH INC-CLASS A (ACMR)",
                "ACCENTURE PLC-CL A (ACN)",
                "ACNB CORP (ACNB)",
                "ACORDA THERAPEUTICS INC (ACOR)",
                "ABERDEEN INCOME CREDIT STRAT (ACP)",
                "ARES COMMERCIAL REAL ESTATE (ACRE)",
                "ACLARIS THERAPEUTICS INC (ACRS)",
                "ACELRX PHARMACEUTICALS INC (ACRX)",
                "AMERICAN CAPITAL SENIOR FLOA (ACSF)",
                "AMERICAN CUST SAT CORE ALPHA (ACSI)",
                "ACASTI PHARMA INC (ACST)",
                "ADVISORSHARES VICE ETF (ACT)",
                "ACACIA RESEARCH CORP (ACTG)",
                "ACME UNITED CORP (ACU)",
                "ALLIANZGI DIVERSIFIED INCOME (ACV)",
                "ISHARES EDGE MSCI MULTIFACTO (ACWF)",
                "ISHARES MSCI ACWI ETF (ACWI)",
                "ISHARES EDGE MSCI MIN VOL GL (ACWV)",
                "ISHARES MSCI ACWI EX US ETF (ACWX)",
                "ACXIOM CORP (ACXM)",
                "AEROCENTURY CORP (ACY)",
                "ADAPTIMMUNE THERAPEUTICS-ADR (ADAP)",
                "ADOBE SYSTEMS INC (ADBE)",
                "AGREE REALTY CORP (ADC)",
                "ADVANCED EMISSIONS SOLUTIONS (ADES)",
                "ANALOG DEVICES INC (ADI)",
                "ARCHER-DANIELS-MIDLAND CO (ADM)",
                "ADMA BIOLOGICS INC (ADMA)",
                "ADAMIS PHARMACEUTICALS CORP (ADMP)",
                "ADAMAS PHARMACEUTICALS INC (ADMS)",
                "ADIENT PLC (ADNT)",
                "ADOMANI INC (ADOM)",
                "AUTOMATIC DATA PROCESSING (ADP)",
                "BLDRS ASIA 50 ADR INDEX FUND (ADRA)",
                "BLDRS DEV MKTS 100 ADR INDEX (ADRD)",
                "BLDRS EMER MKTS 50 ADR INDEX (ADRE)",
                "ADURO BIOTECH INC (ADRO)",
                "BLDRS EUROPE 100 ADR INDEX (ADRU)",
                "ALLIANCE DATA SYSTEMS CORP (ADS)",
                "AUTODESK INC (ADSK)",
                "ADVANCED DISPOSAL SERVICES I (ADSW)",
                "ADT INC (ADT)",
                "ADTRAN INC (ADTN)",
                "ADDUS HOMECARE CORP (ADUS)",
                "ADVERUM BIOTECHNOLOGIES INC (ADVM)",
                "ADAMS DIVERSIFIED EQUITY (ADX)",
                "ADVAXIS INC (ADXS)",
                "DB AGRICULTURE SHORT ETN (ADZ)",
                "ADAMS RESOURCES & ENERGY INC (AE)",
                "AMEREN CORPORATION (AEE)",
                "AEGON N.V.-NY REG SHR (AEG)",
                "AEGION CORP (AEGN)",
                "AEHR TEST SYSTEMS (AEHR)",
                "ADVANCED ENERGY INDUSTRIES (AEIS)",
                "AMERICAN EQUITY INVT LIFE HL (AEL)",
                "AGNICO EAGLE MINES LTD (AEM)",
                "AETHLON MEDICAL INC (AEMD)",
                "AMERICAN EAGLE OUTFITTERS (AEO)",
                "AMERICAN ELECTRIC POWER (AEP)",
                "AERCAP HOLDINGS NV (AER)",
                "AERIE PHARMACEUTICALS INC (AERI)",
                "AES CORP (AES)",
                "AETNA INC (AET)",
                "AMERICAN ELECTRIC TECHNOLOGI (AETI)",
                "ADDVANTAGE TECHNOLOGIES GRP (AEY)",
                "AETERNA ZENTARIS INC (AEZS)",
                "ALLIANCE NATIONAL MUNI INC (AFB)",
                "AMERICAN FINANCIAL GROUP INC (AFG)",
                "ATLAS FINANCIAL HOLDINGS INC (AFH)",
                "ARMSTRONG FLOORING INC (AFI)",
                "VANECK VECTORS AFRICA INDEX (AFK)",
                "AFLAC INC (AFL)",
                "AFFIMED NV (AFMD)",
                "AMTRUST FINANCIAL SERVICES (AFSI)",
                "APOLLO SENIOR FLOATING RATE (AFT)",
                "CSOP FTSE CHINA A50 ETF (AFTY)",
                "FIRST MAJESTIC SILVER CORP (AG)",
                "ADVENT CLAYMORE CONVERTIBLE (AGC)",
                "AGCO CORP (AGCO)",
                "ALPINE GLOBAL DYNAMIC DIVIDE (AGD)",
                "AGENUS INC (AGEN)",
                "DB AGRICULTURE LONG ETN (AGF)",
                "AGROFRESH SOLUTIONS INC (AGFS)",
                "ISHARES CORE U.S. AGGREGATE (AGG)",
                "IQ ENHANCED CORE BOND US ETF (AGGE)",
                "IQ ENHANCED CORE PLUS BOND U (AGGP)",
                "WISDOMTREE BARCLAYS YIELD EN (AGGY)",
                "ALAMOS GOLD INC-CLASS A (AGI)",
                "ARGO GROUP INTERNATIONAL (AGII)",
                "AGIOS PHARMACEUTICALS INC (AGIO)",
                "AEGLEA BIOTHERAPEUTICS INC (AGLE)",
                "FEDERAL AGRIC MTG CORP-CL C (AGM)",
                "FEDERAL AGRIC MTG CORP-CL A (AGM.A)",
                "AGM GROUP HOLDINGS INC (AGMH)",
                "ALLERGAN PLC (AGN)",
                "AGNC INVESTMENT CORP (AGNC)",
                "WISDOMTREE BARCLAYS NEGATIVE (AGND)",
                "ASSURED GUARANTY LTD (AGO)",
                "PROSHARES ULTRA SILVER (AGQ)",
                "AVANGRID INC (AGR)",
                "ADECOAGRO SA (AGRO)",
                "AGILE THERAPEUTICS INC (AGRX)",
                "PLAYAGS INC (AGS)",
                "ISHARES ARGENTINA (AGT)",
                "APPLIED GENETIC TECHNOLOGIES (AGTC)",
                "ARGAN INC (AGX)",
                "AGILYSYS INC (AGYS)",
                "ISHARES AGENCY BOND ETF (AGZ)",
                "WISDOMTREE BARCLAYS INTEREST (AGZD)",
                "A H BELO CORP-A (AHC)",
                "ALLIANCE HOLDINGS GP LP (AHGP)",
                "ARMADA HOFFLER PROPERTIES IN (AHH)",
                "ASPEN INSURANCE HOLDINGS LTD (AHL)",
                "AVISTA HEALTHCARE PUBLIC-A (AHPA)",
                "AVISTA HEALTHCARE PUBLIC ACQ (AHPAU)",
                "ALLIED HEALTHCARE PRODUCTS (AHPI)",
                "ASHFORD HOSPITALITY TRUST (AHT)",
                "ARLINGTON ASSET INVESTMENT-A (AI)",
                "ISHARES ASIA 50 ETF (AIA)",
                "AI POWERED EQUITY ETF (AIEQ)",
                "APOLLO TACTICAL INCOME FUND (AIF)",
                "AMERICAN INTERNATIONAL GROUP (AIG)",
                "SENMIAO TECHNOLOGY LTD (AIHS)",
                "ALTRA INDUSTRIAL MOTION CORP (AIMC)",
                "AIMMUNE THERAPEUTICS INC (AIMT)",
                "ALBANY INTL CORP-CL A (AIN)",
                "ASHFORD INC (AINC)",
                "APOLLO INVESTMENT CORP (AINV)",
                "PRECISION THERAPEUTICS INC (AIPT)",
                "AAR CORP (AIR)",
                "AIRGAIN INC (AIRG)",
                "AIR INDUSTRIES GROUP (AIRI)",
                "FIRST TRUST RBA AMERICAN IND (AIRR)",
                "AIR T INC (AIRT)",
                "APPLIED INDUSTRIAL TECH INC (AIT)",
                "APARTMENT INVT & MGMT CO -A (AIV)",
                "ASSURANT INC (AIZ)",
                "ARTHUR J GALLAGHER & CO (AJG)",
                "AEROJET ROCKETDYNE HOLDINGS (AJRD)",
                "GREAT AJAX CORP (AJX)",
                "AKAMAI TECHNOLOGIES INC (AKAM)",
                "ACHAOGEN INC (AKAO)",
                "AKEBIA THERAPEUTICS INC (AKBA)",
                "AKCEA THERAPEUTICS INC (AKCA)",
                "AKERS BIOSCIENCES INC (AKER)",
                "ASANKO GOLD INC (AKG)",
                "EMBOTELLADORA ANDINA-ADR A (AKO.A)",
                "EMBOTELLADORA ANDINA-ADR B (AKO.B)",
                "ALLIANCE CALIF MUNI INCOME (AKP)",
                "ACADIA REALTY TRUST (AKR)",
                "AKORN INC (AKRX)",
                "AK STEEL HOLDING CORP (AKS)",
                "AKOUSTIS TECHNOLOGIES INC (AKTS)",
                "AKARI THERAPEUTICS PLC-ADR (AKTX)",
                "AIR LEASE CORP (AL)",
                "ALBEMARLE CORP (ALB)",
                "ALBIREO PHARMA INC (ALBO)",
                "ALICO INC (ALCO)",
                "WISDOMTREE ASIA LOCAL DEBT (ALD)",
                "ALDER BIOPHARMACEUTICALS INC (ALDR)",
                "ALDEYRA THERAPEUTICS INC (ALDX)",
                "ALLETE INC (ALE)",
                "ALEXANDER & BALDWIN INC (ALEX)",
                "ALPHACLONE ALTERNATIVE ALPHA (ALFA)",
                "ALPHACLONE INTERNATIONAL ETF (ALFI)",
                "ALAMO GROUP INC (ALG)",
                "ALIGN TECHNOLOGY INC (ALGN)",
                "ALLEGIANT TRAVEL CO (ALGT)",
                "ALIMERA SCIENCES INC (ALIM)",
                "ALJ REGIONAL HOLDINGS INC (ALJJ)",
                "ALASKA AIR GROUP INC (ALK)",
                "ALKERMES PLC (ALKS)",
                "ALLSTATE CORP (ALL)",
                "ALLEGION PLC (ALLE)",
                "ALLOT COMMUNICATIONS LTD (ALLT)",
                "ALLY FINANCIAL INC (ALLY)",
                "AMERICAN LORAIN CORP (ALN)",
                "ALLENA PHARMACEUTICALS INC (ALNA)",
                "ALNYLAM PHARMACEUTICALS INC (ALNY)",
                "ALIO GOLD INC (ALO)",
                "ANALOGIC CORP (ALOG)",
                "ASTRONOVA INC (ALOT)",
                "ALPINE IMMUNE SCIENCES INC (ALPN)",
                "ALLIQUA BIOMEDICAL INC (ALQA)",
                "ALARM.COM HOLDINGS INC (ALRM)",
                "AILERON THERAPEUTICS INC (ALRN)",
                "ALASKA COMM SYSTEMS GROUP (ALSK)",
                "ALLISON TRANSMISSION HOLDING (ALSN)",
                "ALTIMMUNE INC (ALT)",
                "ALTAIR ENGINEERING INC - A (ALTR)",
                "PRSHR MRNGSTR ALT SOL ETF (ALTS)",
                "GLOBAL X SUPERDIVIDEND ALTER (ALTY)",
                "AUTOLIV INC (ALV)",
                "ALEXANDER'S INC (ALX)",
                "ALEXION PHARMACEUTICALS INC (ALXN)",
                "ALZHEON INC (ALZH)",
                "ANTERO MIDSTREAM PARTNERS LP (AM)",
                "AMAG PHARMACEUTICALS INC (AMAG)",
                "APPLIED MATERIALS INC (AMAT)",
                "AMBARELLA INC (AMBA)",
                "AMBAC FINANCIAL GROUP INC (AMBC)",
                "AMBER ROAD INC (AMBR)",
                "AMC ENTERTAINMENT HLDS-CL A (AMC)",
                "ISHARES RUSSELL 1000 US REV (AMCA)",
                "AIRMEDIA GROUP INC-ADR (AMCN)",
                "AMC NETWORKS INC-A (AMCX)",
                "ADVANCED MICRO DEVICES (AMD)",
                "AMEDICA CORP (AMDA)",
                "AMETEK INC (AME)",
                "AMEDISYS INC (AMED)",
                "APOLLO MEDICAL HOLDINGS INC (AMEH)",
                "AFFILIATED MANAGERS GROUP (AMG)",
                "AMGEN INC (AMGN)",
                "ANTERO MIDSTREAM GP LP (AMGP)",
                "AMERICAN HOMES 4 RENT- A (AMH)",
                "AMERICAN MIDSTREAM PARTNERS (AMID)",
                "JPMORGAN ALERIAN MLP INDEX (AMJ)",
                "X-LINKS 2XLEVRG ALERIAN MLP (AMJL)",
                "AMKOR TECHNOLOGY INC (AMKR)",
                "ALERIAN MLP ETF (AMLP)",
                "ALLIANCE MMA INC (AMMA)",
                "AMN HEALTHCARE SERVICES INC (AMN)",
                "AMER NATL BNKSHS/DANVILLE VA (AMNB)",
                "ALLIED MOTION TECHNOLOGIES (AMOT)",
                "AMERICA MOVIL-ADR SERIES A (AMOV)",
                "AMERIPRISE FINANCIAL INC (AMP)",
                "AMPIO PHARMACEUTICALS INC (AMPE)",
                "AMPHASTAR PHARMACEUTICALS IN (AMPH)",
                "ALTA MESA RESOURCES INC (AMR)",
                "AMERICAN RIVER BANKSHRS (CA) (AMRB)",
                "AMERESCO INC-CL A (AMRC)",
                "AMERI HOLDINGS INC (AMRH)",
                "A-MARK PRECIOUS METALS INC (AMRK)",
                "AMARIN CORP PLC -ADR (AMRN)",
                "AMYRIS INC (AMRS)",
                "AMERICAN SHARED HOSPITAL SER (AMS)",
                "AMERICAN SUPERCONDUCTOR CORP (AMSC)",
                "AMERISAFE INC (AMSF)",
                "AMERICAN SOFTWARE INC-CL A (AMSWA)",
                "AMERICAN TOWER CORP (AMT)",
                "TD AMERITRADE HOLDING CORP (AMTD)",
                "AEMETIS INC (AMTX)",
                "ETRACS ALERIAN MLP ETN (AMU)",
                "ETRACS ALERIAN MLP IND SER B (AMUB)",
                "AMERICAN WOODMARK CORP (AMWD)",
                "AMERICA MOVIL-SPN ADR CL L (AMX)",
                "INFRACAP MLP ETF (AMZA)",
                "AMAZON.COM INC (AMZN)",
                "AUTONATION INC (AN)",
                "ANAPTYSBIO INC (ANAB)",
                "AMERICAN NATIONAL INSURANCE (ANAT)",
                "ANCHOR BANCORP (ANCB)",
                "ACCESS NATIONAL CORP (ANCX)",
                "ANDERSONS INC/THE (ANDE)",
                "ANDEAVOR (ANDV)",
                "ANDEAVOR LOGISTICS LP (ANDX)",
                "ARISTA NETWORKS INC (ANET)",
                "ABERCROMBIE & FITCH CO-CL A (ANF)",
                "AMIRA NATURE FOODS LTD (ANFI)",
                "ANGI HOMESERVICES INC- A (ANGI)",
                "VANECK VECTORS FALLEN ANGEL (ANGL)",
                "ANGIODYNAMICS INC (ANGO)",
                "ANWORTH MORTGAGE ASSET CORP (ANH)",
                "ANIKA THERAPEUTICS INC (ANIK)",
                "ANI PHARMACEUTICALS INC (ANIP)",
                "ANSYS INC (ANSS)",
                "ANTHERA PHARMACEUTICALS INC (ANTH)",
                "ANTHEM INC (ANTM)",
                "AEGEAN MARINE PETROLEUM NETW (ANW)",
                "SPHERE 3D CORP (ANY)",
                "ISHARES CORE AGGRESSIVE ALLO (AOA)",
                "AMERICAN OUTDOOR BRANDS CORP (AOBC)",
                "ALPINE TOTAL DYNAMIC DIVIDEN (AOD)",
                "ALLIANCE ONE INTERNATIONAL (AOI)",
                "ISHARES CORE CONSERVATIVE AL (AOK)",
                "ISHARES CORE MODERATE ALLOCA (AOM)",
                "AON PLC (AON)",
                "ISHARES CORE GROWTH ALLOCATI (AOR)",
                "SMITH (A.O.) CORP (AOS)",
                "ALPHA & OMEGA SEMICONDUCTOR (AOSL)",
                "AMPCO-PITTSBURGH CORP (AP)",
                "APACHE CORP (APA)",
                "ARTISAN PARTNERS ASSET MA -A (APAM)",
                "ASIA PACIFIC FUND INC (APB)",
                "ANADARKO PETROLEUM CORP (APC)",
                "AIR PRODUCTS & CHEMICALS INC (APD)",
                "APPLIED DNA SCIENCES INC (APDN)",
                "AMERICAN PUBLIC EDUCATION (APEI)",
                "APOLLO ENDOSURGERY INC (APEN)",
                "MORGAN STANLEY ASIA PACIFIC (APF)",
                "AMPHENOL CORP-CL A (APH)",
                "AMPLIPHI BIOSCIENCES CORP (APHB)",
                "APPLE HOSPITALITY REIT INC (APLE)",
                "ARCHROCK PARTNERS LP (APLP)",
                "APELLIS PHARMACEUTICALS INC (APLS)",
                "APOLLO GLOBAL MANAGEMENT - A (APO)",
                "APOGEE ENTERPRISES INC (APOG)",
                "CELLECT BIOTECHNOLOGY LT-ADR (APOP)",
                "APPFOLIO INC - A (APPF)",
                "APPIAN CORP (APPN)",
                "DIGITAL TURBINE INC (APPS)",
                "APRICUS BIOSCIENCES INC (APRI)",
                "BLUE APRON HOLDINGS INC-A (APRN)",
                "ALPHA PRO TECH LTD (APT)",
                "APPTIO INC - CLASS A (APTI)",
                "APTOSE BIOSCIENCES INC (APTO)",
                "PREFERRED APARTMENT COMMUN-A (APTS)",
                "APTIV PLC (APTV)",
                "AMERIGAS PARTNERS-LP (APU)",
                "APTEVO THERAPEUTICS INC (APVO)",
                "ASIA PACIFIC WIRE & CABLE (APWC)",
                "AQUANTIA CORP (AQ)",
                "AQUABOUNTY TECHNOLOGIES (AQB)",
                "AQUA METALS INC (AQMS)",
                "ALGONQUIN POWER & UTILITIES (AQN)",
                "EVOQUA WATER TECHNOLOGIES CO (AQUA)",
                "AQUINOX PHARMACEUTICALS INC (AQXP)",
                "ANTERO RESOURCES CORP (AR)",
                "AMERICAN RENAL ASSOCIATES HO (ARA)",
                "ACCURAY INC (ARAY)",
                "ARC DOCUMENT SOLUTIONS INC (ARC)",
                "ARCBEST CORP (ARCB)",
                "ARES CAPITAL CORP (ARCC)",
                "ARCH COAL INC - A (ARCH)",
                "APPLIANCE RECYCLING CTRS AMR (ARCI)",
                "ARROW RESERVE CAP MANAG ETF (ARCM)",
                "ARCOS DORADOS HOLDINGS INC-A (ARCO)",
                "ARCTURUS THERAPEUTICS LTD (ARCT)",
                "ARC GROUP WORLDWIDE INC (ARCW)",
                "ARDAGH GROUP SA (ARD)",
                "ARES DYNAMIC CREDIT ALLOCATI (ARDC)",
                "ARADIGM CORP (ARDM)",
                "ARDELYX INC (ARDX)",
                "ALEXANDRIA REAL ESTATE EQUIT (ARE)",
                "ARES MANAGEMENT LP (ARES)",
                "APPROACH RESOURCES INC (AREX)",
                "ARGOS THERAPEUTICS INC (ARGS)",
                "GLOBAL X MSCI ARGENTINA ETF (ARGT)",
                "ARGENX SE - ADR (ARGX)",
                "APOLLO COMMERCIAL REAL ESTAT (ARI)",
                "AMERICAN RAILCAR INDUSTRIES (ARII)",
                "ARK GENOMIC REVL MULT-SECTOR (ARKG)",
                "ARK INNOVATION ETF (ARKK)",
                "ARK INDUSTRIAL INNOVATION (ARKQ)",
                "ARK RESTAURANTS CORP (ARKR)",
                "ARK WEB X.O ETF (ARKW)",
                "AMERICAN REALTY INVESTORS IN (ARL)",
                "ALLIANCE RESOURCE PARTNERS (ARLP)",
                "ARALEZ PHARMACEUTICALS INC (ARLZ)",
                "ARAMARK (ARMK)",
                "ARMO BIOSCIENCES INC (ARMO)",
                "ARENA PHARMACEUTICALS INC (ARNA)",
                "ARCONIC INC (ARNC)",
                "ARCHROCK INC (AROC)",
                "ARROW FINANCIAL CORP (AROW)",
                "ARQULE INC (ARQL)",
                "ARMOUR RESIDENTIAL REIT INC (ARR)",
                "ARRIS INTERNATIONAL PLC (ARRS)",
                "ARRAY BIOPHARMA INC (ARRY)",
                "ARTESIAN RESOURCES CORP-CL A (ARTNA)",
                "ART'S-WAY MANUFACTURING CO (ARTW)",
                "AROTECH CORP (ARTX)",
                "ARROW ELECTRONICS INC (ARW)",
                "ARROWHEAD PHARMACEUTICALS IN (ARWR)",
                "ASA GOLD AND PRECIOUS METALS (ASA)",
                "ASSOCIATED BANC-CORP (ASB)",
                "ARDMORE SHIPPING CORP (ASC)",
                "ASCENT CAPITAL GROUP INC-A (ASCMA)",
                "GLOBAL X FTSE SOUTHEAST ASIA (ASEA)",
                "FLEXSHARES REAL ASSETS FUND (ASET)",
                "ASTA FUNDING INC (ASFI)",
                "LIBERTY ALL-STAR GROWTH FD (ASG)",
                "ASGN INC (ASGN)",
                "ASHLAND GLOBAL HOLDINGS INC (ASH)",
                "XTRACKERS HARVEST CSI 300 CH (ASHR)",
                "XTRACKERS HARVEST CSI 500 CH (ASHS)",
                "XTRACKERS CSI 300 CHINA A-SH (ASHX)",
                "ADVANSIX INC (ASIX)",
                "AVINO SILVER & GOLD MINES (ASM)",
                "ASSEMBLY BIOSCIENCES INC (ASMB)",
                "ASML HOLDING NV-NY REG SHS (ASML)",
                "ASCENA RETAIL GROUP INC (ASNA)",
                "ASCENDIS PHARMA A/S - ADR (ASND)",
                "ARSANIS INC (ASNS)",
                "ASPEN AEROGELS INC (ASPN)",
                "ALTISOURCE PORTFOLIO SOL (ASPS)",
                "ASPEN GROUP INC (ASPU)",
                "GRUPO AEROPORTUARIO SUR-ADR (ASR)",
                "AMERISERV FINANCIAL INC (ASRV)",
                "ASTERIAS BIOTHERAPEUTICS (AST)",
                "ASTROTECH CORP (ASTC)",
                "ASTEC INDUSTRIES INC (ASTE)",
                "ASURE SOFTWARE INC (ASUR)",
                "ASV HOLDINGS INC (ASV)",
                "ASE INDUSTRIAL HLDG-ADR-W/I (ASX#)",
                "AMTECH SYSTEMS INC (ASYS)",
                "ATLANTIC POWER CORP (AT)",
                "ATLANTIC ACQUISITION CORP (ATAC)",
                "ATLANTIC ACQUISITION COR-RTS (ATACR)",
                "ATLANTIC ACQUISITION COR - U (ATACU)",
                "ATA INC-ADR (ATAI)",
                "AMERICA FIRST MULTIFAMILY IN (ATAX)",
                "ALPHATEC HOLDINGS INC (ATEC)",
                "A10 NETWORKS INC (ATEN)",
                "ADTALEM GLOBAL EDUCATION INC (ATGE)",
                "ATHENE HOLDING LTD-CLASS A (ATH)",
                "AUTOHOME INC-ADR (ATHM)",
                "ATHENAHEALTH INC (ATHN)",
                "ATHERSYS INC (ATHX)",
                "ALLEGHENY TECHNOLOGIES INC (ATI)",
                "ATKORE INTERNATIONAL GROUP I (ATKR)",
                "ATLANTICUS HOLDINGS CORP (ATLC)",
                "AMES NATIONAL CORP (ATLO)",
                "BARCLAYS ETN+ SELECT MLP ETN (ATMP)",
                "ATN INTERNATIONAL INC (ATNI)",
                "ACTINIUM PHARMACEUTICALS INC (ATNM)",
                "ATHENEX INC (ATNX)",
                "ATMOS ENERGY CORP (ATO)",
                "ATOMERA INC (ATOM)",
                "ATOSSA GENETICS INC (ATOS)",
                "APTARGROUP INC (ATR)",
                "ATARA BIOTHERAPEUTICS INC (ATRA)",
                "ATRICURE INC (ATRC)",
                "ATRION CORPORATION (ATRI)",
                "ASTRONICS CORP (ATRO)",
                "ANTARES PHARMA INC (ATRS)",
                "AIR TRANSPORT SERVICES GROUP (ATSG)",
                "ATENTO SA (ATTO)",
                "ATTUNITY LTD (ATTU)",
                "ACTUANT CORP-A (ATU)",
                "ALTICE USA INC- A (ATUS)",
                "ACORN INTERNATIONAL INC-ADR (ATV)",
                "ACTIVISION BLIZZARD INC (ATVI)",
                "AVENUE THERAPEUTICS INC (ATXI)",
                "ANGLOGOLD ASHANTI-SPON ADR (AU)",
                "AUBURN NATL BANCORPORATION (AUBN)",
                "AUDIOCODES LTD (AUDC)",
                "AURYN RESOURCES INC (AUG)",
                "GOLDEN MINERALS CO (AUMN)",
                "AU OPTRONICS CORP-SPON ADR (AUO)",
                "AURINIA PHARMACEUTICALS INC (AUPH)",
                "WISDOMTREE AUSTRALIA DIVIDEN (AUSE)",
                "AUTOWEB INC (AUTO)",
                "YAMANA GOLD INC (AUY)",
                "AVISTA CORP (AVA)",
                "GRUPO AVAL ACCIONES Y VALORE (AVAL)",
                "AEROVIRONMENT INC (AVAV)",
                "AVALONBAY COMMUNITIES INC (AVB)",
                "AMERICAN VANGUARD CORP (AVD)",
                "AVADEL PHARMACEUTICALS PLC (AVDL)",
                "AVEO PHARMACEUTICALS INC (AVEO)",
                "BROADCOM INC (AVGO)",
                "AVINGER INC (AVGR)",
                "AVIANCA HOLDINGS SA-SPON ADR (AVH)",
                "AV HOMES INC (AVHI)",
                "AVID TECHNOLOGY INC (AVID)",
                "ADVENT CLAYMORE CVT SEC& INC (AVK)",
                "AVIAT NETWORKS INC (AVNW)",
                "AVON PRODUCTS INC (AVP)",
                "AVNET INC (AVT)",
                "AVX CORP (AVX)",
                "ANAVEX LIFE SCIENCES CORP (AVXL)",
                "AVEXIS INC (AVXS)",
                "AVERY DENNISON CORP (AVY)",
                "AVAYA HOLDINGS CORP (AVYA)",
                "ALLIANCEBERNSTEIN GL HI INC (AWF)",
                "ARMSTRONG WORLD INDUSTRIES (AWI)",
                "AMERICAN WATER WORKS CO INC (AWK)",
                "ALPINE GLOBAL PREMIER PROPER (AWP)",
                "AMERICAN STATES WATER CO (AWR)",
                "AWARE INC/MASS (AWRE)",
                "AVALON HOLDINGS CORP-A (AWX)",
                "ABRAXAS PETROLEUM CORP (AXAS)",
                "ACCELERATE DIAGNOSTICS INC (AXDX)",
                "ANIXTER INTERNATIONAL INC (AXE)",
                "AXOGEN INC (AXGN)",
                "WISDOMTREE ASIA-PACIFIC EX-J (AXJL)",
                "ISHARES EDGE MSCI MIN VOL AS (AXJV)",
                "AMERICAN AXLE & MFG HOLDINGS (AXL)",
                "AXOVANT SCIENCES LTD (AXON)",
                "AMERICAN EXPRESS CO (AXP)",
                "AMREP CORP (AXR)",
                "AXIS CAPITAL HOLDINGS LTD (AXS)",
                "AXSOME THERAPEUTICS INC (AXSM)",
                "AXALTA COATING SYSTEMS LTD (AXTA)",
                "AXT INC (AXTI)",
                "ALEXCO RESOURCE CORP (AXU)",
                "ATLANTICA YIELD PLC (AY)",
                "ACUITY BRANDS INC (AYI)",
                "AIRCASTLE LTD (AYR)",
                "AYTU BIOSCIENCE INC (AYTU)",
                "ALTERYX INC - CLASS A (AYX)",
                "ASTRAZENECA PLC-SPONS ADR (AZN)",
                "AUTOZONE INC (AZO)",
                "ASPEN TECHNOLOGY INC (AZPN)",
                "AZURE POWER GLOBAL LTD (AZRE)",
                "AZURRX BIOPHARMA INC (AZRX)",
                "AZUL SA-ADR (AZUL)",
                "AZZ INC (AZZ)",
                "BARNES GROUP INC (B)",
                "BOEING CO/THE (BA)",
                "POWERSHARES TAXABLE MUNICIPA (BAB)",
                "ALIBABA GROUP HOLDING-SP ADR (BABA)",
                "NATUS MEDICAL INC (BABY)",
                "BANK OF AMERICA CORP (BAC)",
                "BLACKROCK MUNICIPAL INCOME I (BAF)",
                "BOOZ ALLEN HAMILTON HOLDINGS (BAH)",
                "BRASKEM SA-SPON ADR (BAK)",
                "IPATHR SERIES B BLOOMBERG CO (BALB)",
                "BROOKFIELD ASSET MANAGE-CL A (BAM)",
                "BANC OF CALIFORNIA INC (BANC)",
                "BANDWIDTH INC-CLASS A (BAND)",
                "BANCFIRST CORP (BANF)",
                "BANNER CORPORATION (BANR)",
                "STONECASTLE FINANCIAL CORP (BANX)",
                "CREDICORP LTD (BAP)",
                "GRANITESHARES GOLD TRUST (BAR)",
                "BASIC ENERGY SERVICES INC (BAS)",
                "BIOANALYTICAL SYSTEMS INC (BASI)",
                "LIBERTY MEDIA CORP-BRAVES A (BATRA)",
                "LIBERTY MEDIA CORP-BRAVES C (BATRK)",
                "BAXTER INTERNATIONAL INC (BAX)",
                "BLACKBERRY LTD (BB)",
                "BED BATH & BEYOND INC (BBBY)",
                "VIRTUS LIFESCI BIOTECH CLINI (BBC)",
                "BANCO BRADESCO-ADR (BBD)",
                "BANCO BRADESCO-ADR (BBDO)",
                "BLACKROCK MUNICIPAL INCOME (BBF)",
                "BEASLEY BROADCAST GRP INC -A (BBGI)",
                "VANECK VECTORS BIOTECH ETF (BBH)",
                "BLACKROCK MUNI BOND TRUST (BBK)",
                "BHP BILLITON PLC-ADR (BBL)",
                "BLACKROCK TAXABLE MUNICIPAL (BBN)",
                "BLACK BOX CORP (BBOX)",
                "VIRTUS LIFESCI BIOTECH PRODU (BBP)",
                "COLUMBIA BEYOND BRICS ETF (BBRC)",
                "BRAVO BRIO RESTAURANT GROUP (BBRG)",
                "BARRETT BUSINESS SVCS INC (BBSI)",
                "BB&T CORP (BBT)",
                "BROOKFIELD BUSINESS PT-UNIT (BBU)",
                "BANCO BILBAO VIZCAYA-SP ADR (BBVA)",
                "BUILD-A-BEAR WORKSHOP INC (BBW)",
                "BBX CAPITAL CORP (BBX)",
                "BEST BUY CO INC (BBY)",
                "BRUNSWICK CORP (BC)",
                "BISON CAPITAL ACQUISITION CO (BCAC)",
                "BISON CAPITAL ACQUISITION-RT (BCACR)",
                "BISON CAPITAL ACQUISITION CO (BCACU)",
                "BCB BANCORP INC (BCBP)",
                "BOISE CASCADE CO (BCC)",
                "ETFS BBG CMDTY LG DT K-1 FRE (BCD)",
                "BCE INC (BCE)",
                "BONANZA CREEK ENERGY INC (BCEI)",
                "BANCO DE CHILE-ADR (BCH)",
                "ETFS BBG ALL CMDTY K-1 FREE (BCI)",
                "BRAINSTORM CELL THERAPEUTICS (BCLI)",
                "IPATH PURE BETA BROAD CMDTY (BCM)",
                "BRINK'S CO/THE (BCO)",
                "B COMMUNICATIONS LTD (BCOM)",
                "BLUCORA INC (BCOR)",
                "BRIGHTCOVE (BCOV)",
                "BALCHEM CORP (BCPC)",
                "BLUE CAPITAL REINSURANCE HOL (BCRH)",
                "BIOCRYST PHARMACEUTICALS INC (BCRX)",
                "BARCLAYS PLC-SPONS ADR (BCS)",
                "BANCORP 34 INC (BCTF)",
                "BANCROFT FUND LTD (BCV)",
                "BLACKROCK RESOURCES & COMMOD (BCX)",
                "BELDEN INC (BDC)",
                "ETRACS 2X WELLS FARGO BDCI (BDCL)",
                "ETRACS WELLS FARGO BDCI ETN (BDCS)",
                "ETRACS WELL FARGO BDC SER B (BDCZ)",
                "DB BASE METALS DOUBLE LONG (BDD)",
                "BRIDGE BANCORP INC (BDGE)",
                "BLACKROCK ENHANCED EQUITY DI (BDJ)",
                "FLANIGAN'S ENTERPRISES INC (BDL)",
                "BRANDYWINE REALTY TRUST (BDN)",
                "BLONDER TONGUE LABORATORIES (BDR)",
                "BREAKWAVE DRY BULK SHIPPING (BDRY)",
                "BIODELIVERY SCIENCES INTL (BDSI)",
                "BECTON DICKINSON AND CO (BDX)",
                "BIOTELEMETRY INC (BEAT)",
                "BEACON ROOFING SUPPLY INC (BECN)",
                "BRIGHT SCHOLAR EDUCATION-ADR (BEDU)",
                "ETFS BBG ENG CMD LG DT K1 FR (BEF)",
                "BELMOND LTD-CLASS A (BEL)",
                "BEL FUSE INC-CL A (BELFA)",
                "BEL FUSE INC-CL B (BELFB)",
                "APTUS BEHAVIORAL MOMENTUM ET (BEMO)",
                "FRANKLIN RESOURCES INC (BEN)",
                "BROOKFIELD RENEWABLE PARTNER (BEP)",
                "BERNSTEIN US RESEARCH FUND (BERN)",
                "BERRY GLOBAL GROUP INC (BERY)",
                "BROWN-FORMAN CORP-CLASS A (BF.A)",
                "BROWN-FORMAN CORP-CLASS B (BF.B)",
                "BRIGHT HORIZONS FAMILY SOLUT (BFAM)",
                "BANKFINANCIAL CORP (BFIN)",
                "GLOBAL X HEALTH & WELLNESS (BFIT)",
                "BLACKROCK MUNICIPAL INC TRST (BFK)",
                "BLACKROCK FL MUNI 2020 TERM (BFO)",
                "BARRON'S 400 ETF (BFOR)",
                "BBVA BANCO FRANCES SA-ADR (BFR)",
                "BIOFRONTERA AG (BFRA)",
                "SAUL CENTERS INC (BFS)",
                "BUSINESS FIRST BANCSHARES (BFST)",
                "BLACKROCK NEW YORK MUN II (BFY)",
                "BLACKROCK CALIFOR MUNI IN TR (BFZ)",
                "BUNGE LTD (BG)",
                "BLACKSTONE/GSO STRATEGIC C (BGB)",
                "GENERAL CABLE CORP (BGC)",
                "BGC PARTNERS INC-CL A (BGCP)",
                "BIG 5 SPORTING GOODS CORP (BGFV)",
                "BRIGGS & STRATTON (BGG)",
                "BARINGS GL SH DUR HI YLD (BGH)",
                "BIRKS GROUP INC (BGI)",
                "BLACKROCK 2022 GLOBAL INCOME (BGIO)",
                "BEIGENE LTD-ADR (BGNE)",
                "BLACKROCK ENRGY & RES (BGR)",
                "B&G FOODS INC (BGS)",
                "BG STAFFING INC (BGSF)",
                "BLACKROCK FLT RT INC (BGT)",
                "BLACKSTONE/GSO LONG-SHORT CR (BGX)",
                "BLACKROCK ENHANCED INTERNATI (BGY)",
                "BIGLARI HOLDINGS INC (BH)",
                "BARINGTON/HILCO ACQUISITION (BHAC)",
                "BARINGTON/HILCO ACQUIS-RIGHT (BHACR)",
                "BARINGTON/HILCO ACQUISITION (BHACU)",
                "BAR HARBOR BANKSHARES (BHB)",
                "BLUE HILLS BANCORP INC (BHBK)",
                "BENCHMARK ELECTRONICS INC (BHE)",
                "BRIGHTHOUSE FINANCIAL INC (BHF)",
                "BAKER HUGHES A GE CO (BHGE)",
                "BLACKROCK CORE BOND TRUST (BHK)",
                "BERKSHIRE HILLS BANCORP INC (BHLB)",
                "BHP BILLITON LTD-SPON ADR (BHP)",
                "BIOHITECH GLOBAL INC (BHTG)",
                "BLACKROCK VIRGINIA MUNI BOND (BHV)",
                "BIOHAVEN PHARMACEUTICAL HOLD (BHVN)",
                "PROSHARES ULTRA NASD BIOTECH (BIB)",
                "INSPIRE 100 ETF (BIBL)",
                "FIRST TRUST BICK INDEX FUND (BICK)",
                "SOTHEBY'S (BID)",
                "BAIDU INC - SPON ADR (BIDU)",
                "BOULDER GROWTH & INCOME FUND (BIF)",
                "BIG LOTS INC (BIG)",
                "BIOGEN INC (BIIB)",
                "SPDR BBG BARC 1-3 MONTH TBIL (BIL)",
                "BILIBILI INC-SPONSORED ADR (BILI)",
                "BIO-RAD LABORATORIES-A (BIO)",
                "BIO-RAD LABORATORIES -CL B (BIO.B)",
                "BIOCEPT INC (BIOC)",
                "BIOLASE INC (BIOL)",
                "BIOSCRIP INC (BIOS)",
                "BROOKFIELD INFRASTRUCTURE PA (BIP)",
                "PROSHARES ULTRASHORT NAS BIO (BIS)",
                "BLACKROCK MULTI-SECTOR INCOM (BIT)",
                "BITAUTO HOLDINGS LTD-ADR (BITA)",
                "VANGUARD INTERMEDIATE-TERM B (BIV)",
                "VANECK VECTORS BDC INCOME ET (BIZD)",
                "IPATH SERIES B BLOOMBERG NIC (BJJN)",
                "VANECK VECTORS GAMING ETF (BJK)",
                "IPATH SERIES B BLOOMBERG COF (BJO)",
                "BJ'S RESTAURANTS INC (BJRI)",
                "BLACKROCK CALI MUNI 2018 TRM (BJZ)",
                "BANK OF NEW YORK MELLON CORP (BK)",
                "BLACKROCK CAPITAL INVESTMENT (BKCC)",
                "BROOKDALE SENIOR LIVING INC (BKD)",
                "BUCKLE INC/THE (BKE)",
                "BLUEKNIGHT ENERGY PARTNERS L (BKEP)",
                "ISHARES MSCI BRIC ETF (BKF)",
                "BLACK HILLS CORP (BKH)",
                "BLACK KNIGHT INC (BKI)",
                "BANCORP OF NEW JERSEY INC (BKJ)",
                "BLACKROCK MUNI 2020 TERM TRS (BKK)",
                "POWERSHARES SENIOR LOAN (BKLN)",
                "BLACKROCK INVT QUALITY MUNI (BKN)",
                "BOOKING HOLDINGS INC (BKNG)",
                "BARNES & NOBLE INC (BKS)",
                "BANK OF SOUTH CAROLINA CORP (BKSC)",
                "BLACKROCK INCOME TRUST (BKT)",
                "BANKUNITED INC (BKU)",
                "BIO-KEY INTERNATIONAL INC (BKYI)",
                "BLACKLINE INC (BL)",
                "BLUE BIRD CORP (BLBD)",
                "BELLICUM PHARMACEUTICALS INC (BLCM)",
                "REALITY SHRS NASDAQ NEXGEN (BLCN)",
                "TOPBUILD CORP (BLD)",
                "BALLARD POWER SYSTEMS INC (BLDP)",
                "BUILDERS FIRSTSOURCE INC (BLDR)",
                "BLACKROCK MUN INC TRUST II (BLE)",
                "INSPIRE GLOBAL HOPE ETF (BLES)",
                "BIOLIFE SOLUTIONS INC (BLFS)",
                "BLACKROCK NEW YORK MUNI 2018 (BLH)",
                "VIRTUS NEWFLEET DYNAMIC CRED (BLHY)",
                "BRIDGELINE DIGITAL INC (BLIN)",
                "BLACKROCK NEW JERSEY MUNI BD (BLJ)",
                "BLACKROCK INC (BLK)",
                "BLACKBAUD INC (BLKB)",
                "BALL CORP (BLL)",
                "BLOOMIN' BRANDS INC (BLMN)",
                "BSB BANCORP INC/MA (BLMT)",
                "BLINK CHARGING CO (BLNK)",
                "AMPLIFY TRANSFOR DATA SHARIN (BLOK)",
                "BELLEROPHON THERAPEUTICS INC (BLPH)",
                "BIOLINERX LTD-SPONS ADR (BLRX)",
                "BLUEBIRD BIO INC (BLUE)",
                "VANGUARD LONG-TERM BOND ETF (BLV)",
                "BLACKROCK LTD DURATION INC (BLW)",
                "BANCO LATINOAMERICANO COME-E (BLX)",
                "BANCO MACRO SA-ADR (BMA)",
                "BMC STOCK HOLDINGS INC (BMCH)",
                "BLACKROCK HEALTH SCIENCES TR (BME)",
                "BADGER METER INC (BMI)",
                "BMO ELKHORN DWA MLP SI ETN (BMLP)",
                "BANK OF MONTREAL (BMO)",
                "BIOMERICA INC (BMRA)",
                "BANK OF MARIN BANCORP/CA (BMRC)",
                "BIOMARIN PHARMACEUTICAL INC (BMRN)",
                "BEMIS COMPANY (BMS)",
                "BRYN MAWR BANK CORP (BMTC)",
                "BRISTOL-MYERS SQUIBB CO (BMY)",
                "BENEFICIAL BANCORP INC (BNCL)",
                "VANGUARD TOTAL BOND MARKET (BND)",
                "FLEXSHARES CORE SELECT BOND (BNDC)",
                "VANGUARD TOTAL INTL BOND ETF (BNDX)",
                "BARNES & NOBLE EDUCATION INC (BNED)",
                "BENEFITFOCUS INC (BNFT)",
                "BLACKROCK NJ MUNI INCOME TRS (BNJ)",
                "UNITED STATES BRENT OIL FUND (BNO)",
                "BANK OF NOVA SCOTIA (BNS)",
                "BONSO ELECTRONICS INTL INC (BNSO)",
                "BENITEC BIOPHARMA-SP ADR (BNTC)",
                "BLACKROCK NEW YORK MUNI INC (BNY)",
                "BANK OF COMMERCE HOLDINGS (BOCH)",
                "BLACKROCK ENHANCED GLOBAL DI (BOE)",
                "BOFI HOLDING INC (BOFI)",
                "BANK OF HAWAII CORP (BOH)",
                "PROSHARES ULTRA BLOOMBERG NA (BOIL)",
                "BOJANGLES' INC (BOJA)",
                "BOK FINANCIAL CORPORATION (BOKF)",
                "AUDENTES THERAPEUTICS INC (BOLD)",
                "DB BASE METALS DOUBLE SHORT (BOM)",
                "BOSTON OMAHA CORP-CL A (BOMN)",
                "PIMCO ACTIVE BOND EXCHANGE-T (BOND)",
                "DMC GLOBAL INC (BOOM)",
                "NYSE PICKENS OIL RESPONSE ET (BOON)",
                "BOOT BARN HOLDINGS INC (BOOT)",
                "CHINA NEW BORUN CORP-ADR (BORN)",
                "DB BASE METALS SHORT ETN (BOS)",
                "BOS BETTER ON-LINE SOLUTIONS (BOSC)",
                "GLOBAL X FOUNDER-RUN COMPANI (BOSS)",
                "BANK OF THE JAMES FINANCIAL (BOTJ)",
                "GLOBAL X ROBOTICS & ARTIFICI (BOTZ)",
                "BOX INC - CLASS A (BOX)",
                "BOXLIGHT CORP - CLASS A (BOXL)",
                "BP PLC-SPONS ADR (BP)",
                "BOSTON PRIVATE FINL HOLDING (BPFH)",
                "BRIDGEPOINT EDUCATION INC (BPI)",
                "BLACKROCK MUNICIPAL 2018 TRM (BPK)",
                "BUCKEYE PARTNERS LP (BPL)",
                "BLUEPRINT MEDICINES CORP (BPMC)",
                "BP MIDSTREAM PARTNERS LP (BPMP)",
                "BIOPHARMX CORP (BPMX)",
                "POPULAR INC (BPOP)",
                "THE BANK OF PRINCETON (BPRN)",
                "BP PRUDHOE BAY ROYALTY TRUST (BPT)",
                "BIO-PATH HOLDINGS INC (BPTH)",
                "BROOKFIELD PROPERTY PARTNERS (BPY)",
                "BLACKROCK NEW YORK MUNI BOND (BQH)",
                "BROADRIDGE FINANCIAL SOLUTIO (BR)",
                "BLACK RIDGE ACQUISITION CORP (BRAC)",
                "BLACK RIDGE ACQU CORP-RTS (BRACR)",
                "BLACK RIDGE ACQUISITION CORP (BRACU)",
                "BRADY CORPORATION - CL A (BRC)",
                "CRAFT BREW ALLIANCE INC (BREW)",
                "VANECK VECTORS BRAZIL SMALL- (BRF)",
                "BRF SA-ADR (BRFS)",
                "BLUEROCK RESIDENTIAL GROWTH (BRG)",
                "BERNSTEIN GLOBAL RESEARCH FU (BRGL)",
                "BRIDGFORD FOODS CORP (BRID)",
                "BERKSHIRE HATHAWAY INC-CL A (BRK.A)",
                "BERKSHIRE HATHAWAY INC-CL B (BRK.B)",
                "BROOKLINE BANCORP INC (BRKL)",
                "BRUKER CORP (BRKR)",
                "BROOKS AUTOMATION INC (BRKS)",
                "BARNWELL INDUSTRIES INC (BRN)",
                "BROWN & BROWN INC (BRO)",
                "BIG ROCK PARTNERS ACQUISITIO (BRPA)",
                "BIG ROCK PARTNERS ACQUIS-RTS (BRPAR)",
                "BIG ROCK PARTNERS ACQUISITIO (BRPAU)",
                "BORQS TECHNOLOGIES INC (BRQS)",
                "BRISTOW GROUP INC (BRS)",
                "GLOBAL BRASS & COPPER HOLDIN (BRSS)",
                "BRT APARTMENTS CORP (BRT)",
                "BRIXMOR PROPERTY GROUP INC (BRX)",
                "DIREXION DAILY BRAZIL BULL 3 (BRZU)",
                "BANCO SANTANDER-CHILE-ADR (BSAC)",
                "BANCO SANTANDER BRASIL-ADS (BSBR)",
                "PWR BSHR 2018 CP BD (BSCI)",
                "PWR BSHR 2019 CP BD (BSCJ)",
                "PWR BSHR 2020 CP BD (BSCK)",
                "PWR BSHR 2021 CP BD (BSCL)",
                "PWR BSHR 2022 CP BD (BSCM)",
                "PWR BSHR 2023 CP BD (BSCN)",
                "PWR BSHR 2024 CP BD (BSCO)",
                "PWR BSHR 2025 CP BD (BSCP)",
                "PWR BSHR 2026 CP BD (BSCQ)",
                "PWR BSHR 2027 CP BD (BSCR)",
                "BLACKROCK STRATEGIC MUNICIPL (BSD)",
                "BLACKROCK NEW YORK MUNICIPAL (BSE)",
                "BASSETT FURNITURE INDS (BSET)",
                "BRIGHTSPHERE INVESTMENT GROU (BSIG)",
                "PWR BSHR 2018 HI YLD CP BD (BSJI)",
                "PWR BSHR 2019 HI YLD CP BD (BSJJ)",
                "PWR BSHR 2020 HI YLD CP BD (BSJK)",
                "PWR BSHR 2021 HI YLD CP BD (BSJL)",
                "PWR BSHR 2022 HI YLD CP BD (BSJM)",
                "PWR BSHR 2023 HI YLD CP BD (BSJN)",
                "PWR BSHR 2024 HI YLD CP BD (BSJO)",
                "GUGGHM BLTSHR HY CORP 2025 (BSJP)",
                "BLACKSTONE/GSO SENIOR FLOAT (BSL)",
                "BLACK STONE MINERALS LP (BSM)",
                "BANCO SANTANDER MEXICO -ADR (BSMX)",
                "BIOSTAR PHARMACEUTICALS INC (BSPM)",
                "BSQUARE CORP (BSQR)",
                "SIERRA BANCORP (BSRR)",
                "BLACKROCK SCIENCE & TECH TR (BST)",
                "BIOSPECIFICS TECHNOLOGIES (BSTC)",
                "BEST INC - ADR (BSTI)",
                "VANGUARD SHORT-TERM BOND ETF (BSV)",
                "VELOCITY SHARES VIX TAIL RSK (BSWN)",
                "BOSTON SCIENTIFIC CORP (BSX)",
                "BT GROUP PLC-SPON ADR (BT)",
                "BLACKROCK LNG-TM MUN ADV TST (BTA)",
                "BIOXCEL THERAPEUTICS INC (BTAI)",
                "AGFIQ US MARKET NEUTRAL ANTI (BTAL)",
                "BAYTEX ENERGY CORP (BTE)",
                "PRINCIPAL HEALTHCARE INNOV (BTEC)",
                "B2GOLD CORP (BTG)",
                "BRITISH AMERICAN TOB-SP ADR (BTI)",
                "BALLANTYNE STRONG INC (BTN)",
                "JOHN HANCOCK FINANCIAL OPPOR (BTO)",
                "BLACKROCK MUNICIPAL 2030 TAR (BTT)",
                "PEABODY ENERGY CORP (BTU)",
                "BIOTIME INC (BTX)",
                "BLACKROCK CREDIT ALLOCATION (BTZ)",
                "ANHEUSER-BUSCH INBEV-SPN ADR (BUD)",
                "BLUE BUFFALO PET PRODUCTS IN (BUFF)",
                "BLCKRCK UTIL INFRA & PWR OPP (BUI)",
                "BURCON NUTRASCIENCE CORP (BUR)",
                "CHANTICLEER HOLDINGS INC (BURG)",
                "BURLINGTON STORES INC (BURL)",
                "FIRST BUSEY CORP (BUSE)",
                "USCF SUMMERHAVEN SHPEI IN FD (BUY)",
                "USCF SUMMERHAVEN SHPEN INDEX (BUYN)",
                "BUZZ US SENTIMENT LEADERS ET (BUZ)",
                "BRAND VALUE ETF (BVAL)",
                "CIA DE MINAS BUENAVENTUR-ADR (BVN)",
                "BRANDES VALUE NEXTSHARES (BVNSC)",
                "BROADVISION INC (BVSN)",
                "BOVIE MEDICAL CORP (BVX)",
                "BIONDVAX PHARMACEUTICALS-ADR (BVXV)",
                "BABCOCK & WILCOX ENTERPR (BW)",
                "BORGWARNER INC (BWA)",
                "BRIDGEWATER BANCSHARES INC (BWB)",
                "BROADWIND ENERGY INC (BWEN)",
                "BANKWELL FINANCIAL GROUP INC (BWFG)",
                "BRANDYWINEGLOBAL GLOBAL INCO (BWG)",
                "BALDWIN & LYONS INC -CL A (BWINA)",
                "BALDWIN & LYONS INC -CL B (BWINB)",
                "BOWL AMERICA INC-CLASS A (BWL.A)",
                "BOARDWALK PIPELINE PARTNERS (BWP)",
                "SPDR BBG BARC INTL TREASURY (BWX)",
                "BWX TECHNOLOGIES INC (BWXT)",
                "SPDR BBG BARC ST INTL TREAS (BWZ)",
                "BLACKSTONE GROUP LP/THE (BX)",
                "BLUELINX HOLDINGS INC (BXC)",
                "BELLATRIX EXPLORATION LTD (BXE)",
                "BLUEGREEN VACATIONS CORP (BXG)",
                "BLACKSTONE MORTGAGE TRU-CL A (BXMT)",
                "NUVEEN S&P500 BUY-WRT INC FD (BXMX)",
                "BOSTON PROPERTIES INC (BXP)",
                "BANCORPSOUTH BANK (BXS)",
                "BYLINE BANCORP INC (BY)",
                "BOYD GAMING CORP (BYD)",
                "BROADWAY FINANCIAL CORP/DE (BYFC)",
                "ISHARES YIELD OPTIMIZED BOND (BYLD)",
                "BLACKROCK MUNICIPAL INCOME Q (BYM)",
                "BEYONDSPRING INC (BYSI)",
                "WISDOMTREE BRAZILIAN REAL ST (BZF)",
                "BEAZER HOMES USA INC (BZH)",
                "BLACKROCK MARYLAND MUNI BOND (BZM)",
                "PROSHARES ULTRASHORT MSCI BR (BZQ)",
                "BAOZUN INC-SPN ADR (BZUN)",
                "CITIGROUP INC (C)",
                "CA INC (CA)",
                "CORP AMERICA AIRPORTS SA (CAAP)",
                "CHINA AUTOMOTIVE SYSTEMS INC (CAAS)",
                "CABLE ONE INC (CABO)",
                "CAMDEN NATIONAL CORP (CAC)",
                "CREDIT ACCEPTANCE CORP (CACC)",
                "CLEARBRIDGE ALLCAP GRWTH ETF (CACG)",
                "CACI INTERNATIONAL INC -CL A (CACI)",
                "CHINA ADVANCED CONSTRUCTION (CADC)",
                "CADENCE BANCORP (CADE)",
                "CAE INC (CAE)",
                "MORGAN STANLEY CHINA A SHARE (CAF)",
                "8POINT3 ENERGY PARTNERS LP (CAFD)",
                "CONAGRA BRANDS INC (CAG)",
                "CARDINAL HEALTH INC (CAH)",
                "CAI INTERNATIONAL INC (CAI)",
                "CANON INC-SPONS ADR (CAJ)",
                "CHEESECAKE FACTORY INC/THE (CAKE)",
                "CALERES INC (CAL)",
                "CALITHERA BIOSCIENCES INC (CALA)",
                "PACER US SMALL CAP CASH COWS (CALF)",
                "CHINA AUTO LOGISTICS INC (CALI)",
                "MAGICJACK VOCALTEC LTD (CALL)",
                "CAL-MAINE FOODS INC (CALM)",
                "CALIX INC (CALX)",
                "CALAMP CORP (CAMP)",
                "CAMTEK LTD (CAMT)",
                "TEUCRIUM SUGAR FUND (CANE)",
                "CAN FITE BIOPHARMA LTD-ADR (CANF)",
                "BARCLAYS ETN+ SHILLER CAPE (CAPE)",
                "CROSSAMERICA PARTNERS LP (CAPL)",
                "CAPRICOR THERAPEUTICS INC (CAPR)",
                "AVIS BUDGET GROUP INC (CAR)",
                "CARA THERAPEUTICS INC (CARA)",
                "CARBONITE INC (CARB)",
                "CARGURUS INC (CARG)",
                "CAROLINA FINANCIAL CORP (CARO)",
                "CARS.COM INC (CARS)",
                "CAROLINA TRUST BANCSHARES IN (CART)",
                "CARVER BANCORP INC (CARV)",
                "FIRST TRUST NASDAQ GLOBAL AU (CARZ)",
                "CASA SYSTEMS INC (CASA)",
                "META FINANCIAL GROUP INC (CASH)",
                "CASI PHARMACEUTICALS INC (CASI)"};
        final AutoCompleteTextView autoCompleteTextViewCountry = (AutoCompleteTextView)rootView.findViewById(R.id.countries_list);

        ArrayAdapter<String> adapter = new ArrayAdapter<String>(getActivity(),
                android.R.layout.simple_dropdown_item_1line, COUNTRIES);

        autoCompleteTextViewCountry.setAdapter(adapter);
        autoCompleteTextViewCountry.setThreshold(2);


        autoCompleteTextViewCountry.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                autoCompleteTextViewCountry.showDropDown();
            }
        });
/*
        btnSelectedCountry.setOnClickListener(new View.OnClickListener() {
            public void onClick(View arg0) {
                // TODO Auto-generated method stub
                String country=autoCompleteTextViewCountry.getText().toString();
                textViewSelectedCountry.setText("Selected Country: "+country);
            }
        });
        */
        return rootView;
    }
}
